name: Dash App CI

on:
  push:
    branches:
      - main


jobs:
  # Step 1: Test the app using Docker
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_host: ${{ vars.PROXY_HOST }}
          proxy_username: ${{ secrets.USERNAME }}
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull bidhan01/car_prediction_v3:latest
            docker compose -f st125287/docker-compose.yaml down --remove-orphans
            docker compose -f st125287/docker-compose.yaml up -d